### ISSUE TITLE
Provider values not available after app start

### ISSUE THREAD

**Issue by h3po** [fr3ts0n/AndrOBD-Plugin#17]
Using androbd v2.3.3 with sensorprovider v1.0.4 and gpsprovider 1.0.4 I'm not getting GPS_ and ACC_ values after starting the app (in demo mode). Once i toggle the GpsProvider Plugin off/on, the values for GPS appear; those for ACC don't appear even after toggling. In the MqttPublisher, ACC_* items can be selected, but are never published to mqtt. On LineageOS 17.1 (Android 10).

**Comment by h3po** [comment]
I just noticed if i start the plugin apps before androbd, the acc values are available immediately while the gpsprovider still needs a toggle off/on

**Comment by fr3ts0n** [comment]
Thank you for your report.

This behaviour of AndrOBD / plugins is already known to be specific to Android versions >= 10.
It is fixed with AndrOBD >= V2.4.0 and corresponding plugins >= V1.1.0.

These versions are already released, built by FDroid and on their way for FDroid deployment.
They should be available on FDroid within the next days

**Comment by h3po** [comment]
nice! thanks
